services:
  claimrequest.apis:
    image: claimrequest.apis
    build:
      context: .
      dockerfile: ClaimRequest.Apis/Dockerfile
    ports:
      - "5152:8080"
      - "7165:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=claim_request
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pg_data:
  caddy_data:
  caddy_config: