using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace ClaimRequest.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class missingmigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                schema: "public",
                table: "EmailTemplates",
                keyColumn: "Id",
                keyValue: 7);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                schema: "public",
                table: "EmailTemplates",
                columns: new[] { "Id", "Content", "Header", "MainContent" },
                values: new object[,]
                {
                    { 1, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 1", "Main 1" },
                    { 2, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 2", "Main 2" },
                    { 3, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 3", "Main 3" },
                    { 4, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 4", "Main 4" },
                    { 5, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 5", "Main 5" },
                    { 6, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 6", "Main 6" },
                    { 7, "\r\n                    <!DOCTYPE html>\r\n                        <html>\r\n                            <head>\r\n                                <meta charset=\"UTF-8\" />\r\n                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n                                <title>Email Template</title>\r\n                                <link\r\n                                href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\"\r\n                                rel=\"stylesheet\"\r\n                                />\r\n                            </head>\r\n                            <body class=\"bg-gray-100\">\r\n                                <div class=\"max-w-xl mx-auto my-6 bg-white rounded-lg shadow-md\">\r\n                                <div class=\"bg-blue-500 text-white text-center py-4 rounded-t-lg\">\r\n                                    <h1 class=\"text-xl font-bold\">{{header}}</h1>\r\n                                </div>\r\n                                <div class=\"p-6 text-center\">\r\n                                    <p class=\"text-gray-800 text-base\">Hello <b>{{username}}</b>,</p>\r\n                                    <p class=\"text-gray-700 mt-4\">{{content}}</p>\r\n                                </div>\r\n                                <div class=\"bg-gray-100 text-center py-3 rounded-b-lg\">\r\n                                    <p class=\"text-gray-500 text-xs\">\r\n                                        © {{year}} FPT Software Academy. All rights reserved.\r\n                                    </p>\r\n                                    <p>\r\n                                        <a href=\"{{website_link}}\" class=\"text-blue-500 text-xs\"\r\n                                            >Visit our website</a\r\n                                        >\r\n                                    </p>\r\n                                </div>\r\n                            </div>\r\n                        </body>\r\n                    </html>", "Template 7", "Main 7" }
                });
        }
    }
}
